1234567980

: BAR  5 0 DO  I .  LOOP CR ;

: BAZ  3 0 DO  3 0 DO  J . I .  CR LOOP  LOOP ;

: TESTTHIS  DUP 0= IF DROP CR EXIT THEN DUP . 1 - RECURSE ; 5 TESTTHIS

: TEST1  0 BEGIN  DUP . 1 +  DUP 10 = IF EXIT THEN  AGAIN ;

: TEST2  0 BEGIN  DUP . DUP 10 <> WHILE 1 + REPEAT DROP ;

5 TESTTHIS

BAR
BAZ

S" test2.fs" INCLUDED

TEST1 DROP CR
TEST2 CR
.
